### ISSUE TITLE
core: server_id to be changed to long long type

### ISSUE THREAD

**Issue by SurendraPlivo** [kamailio/kamailio#1322]
### Description
we want to give decimal value of ip address to the server_id .When i am converting the ipv6 address to decimal then its bigger then the what integer number defines.so i am not able to get the proper server_id into the database.

#### Reproduction
issue can be reproduced by following steps: 
first get the server_id by converting the ipv6 ip address to decimal so whenever any endpoint register it will store the -1 into database as integer range is reached to limit.

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
version: kamailio 5.0.4 (x86_64/linux) 
flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: unknown 
compiled on 13:58:01 Nov 20 2017 with unknown

```

* **Operating System**:

```
root@ip-172-31-0-35:~# uname -a
Linux ip-172-31-0-35 4.4.0-1022-aws #31-Ubuntu SMP Tue Jun 27 11:27:55 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by SurendraPlivo** [comment]
@miconda to resolve this we need to make many changes to core and might be changes to parser also. we need to make changes to modules that are using the server_id.it will be huge changes but it might be required in future.we can convert int to long long int .in database we can convert int to bigint.

**Comment by miconda** [comment]
The server_id type is integer, which I consider to be more than enough for any very large deployment (the positive range is over 2 billion values, I am quite confident it is more than any foreseeable deployment would have in terms of number of server/kamailio instances).

The scope of server_id is to be fast in matching, not to add too much penalty. Otherwise it could have been a string.

You may want to store a value that is larger than integer, but others later may want to store something else where even long long is enough.

So in my opinion, integer is enough, server id is supposed to be a unique integer value in the deployment, not something else. But I am open to see opinions from others, if they find benefits or drawbacks.

**Comment by miconda** [comment]
Changed the title, because it is a feature request to change a working design for server_id, not an existing issue that needs to be fixed.

**Comment by miconda** [comment]
Closing this one as no interest shown for long time -- if someone wants it, just make a pull request.
