### ISSUE TITLE
cfgutils route_if_exists causing leak

### ISSUE THREAD

**Issue by jchavanton** [kamailio/kamailio#1503]
### Description
cfgutils route_if_exists can leak when
1: using a $var or $avp
2: some functions are called within the called route

#### Reproduction
reproduced on both Kamailio 4.4.x and 5.x

Note that in my tests the route is executed from `rtimer` in case this is part of the problem somehow.
```
modparam("rtimer", "timer", "name=tmetrics;interval=9;mode=1;")
modparam("rtimer", "exec", "timer=tmetrics;route=test")
```
example :
```
route[dummy] {
        xinfo("[dummy]");
        statsd_gauge("dummy_1xx", $stat(1xx_replies));
}
route[test] {
        $var(route_name) = "dummy";
        route_if_exists($var(route_name));
]
```
working alternative
```
route[dummy] {
        xinfo("[dummy]");
        statsd_gauge("dummy_1xx", $stat(1xx_replies));
}
route[test] {
        $var(route_name) = "dummy";
        if (check_route_exists($var(route_name))) {
                     route($var(route_name));
       } 
}
```

#### Debugging Data
```
kamcmd pkg.stats you can see the `real_used` of the timer process with leak every time the route is called
```
reproduced on both Kamailio 4.4.x and 5.x

**Comment by miconda** [comment]
It's rather impossible that $var(...) is leaking, but be aware that its value persists across executions of route blocks, the value is reset only by a new assign.

Then $avp() is using shared memory, so not related to pkg.stats output.

I looked at the code for `route_if_exists` and I discovered that was executing the route block as a top route, not as a sub-route (what route(x) does). I pushed a patch for it. Maybe that was the cause of leak, eventually inside the statsd operation, because route_if_exists doesn't allocate anything itself.

**Comment by jchavanton** [comment]
right, it must be a side effect of having a variable param 
```
kamcmd ps | grep met
2453	RTIMER EXEC child=0 timer=tmetrics
kamcmd pkg.stats | grep -A 5 2453 | grep real
	real_used: 2243864
kamcmd pkg.stats | grep -A 5 2453 | grep real
	real_used: 2244552
```
no luck with the patch ...

**Comment by miconda** [comment]
I pushed the above patch to have a similar behaviour for route_if_exists() like for route(). If the issue still exists, maybe it is better to open a new issue to track it in the context of the latest code.
