### ISSUE TITLE
do not fragment flag

### ISSUE THREAD

**Issue by sergey-safarov** [kamailio/kamailio#1510]
looks as  `do not fragment` flag is applied to TCP transport by default
Later will test on default config.

**Comment by sergey-safarov** [comment]
example of INVITE with `do not fragment` flag is enabled
[mtu.pcapng.gz](https://github.com/kamailio/kamailio/files/1944306/mtu.pcapng.gz)

**Comment by miconda** [comment]
This is not something done in Kamailio, but more about the tcp/os stack implementation. Usually tcp sends with do not fragment flag set in order to adapt to the largest MTU that can be used on the path. Not aware if this is something that can be configured at OS level, but I checked kamailio tcp code and there is no such flag set.

If you want to discuss more, bring this topic to sr-users, there might be other people that know more about system options/how to tune this.

**Comment by sergey-safarov** [comment]
Thanks Daniel (@miconda)
Looks as [this](http://appcrawler.com/wordpress/2014/06/27/net-ipv4-ip_no_pmtu_disc-and-dont-fragment/) case descriptions is same

**Comment by miconda** [comment]
As I get it from that article, then it can be controlled at OS level via:

```
net.ipv4.ip_no_pmtu_disc = 1
```
