### ISSUE TITLE
srdb1: connection string to mongodb too long

### ISSUE THREAD

**Issue by tiglat** [kamailio/kamailio#1545]
### Description

We need to connect to a cluster of mongodb hosts with some specific parameters.
The connection string has length more than 255 characters.
We could not connect to our mongodb.

#### Reproduction

Use very long string for example like bellow

mongo0-pdb-demo.somedomain.com:27017,mongo1-pdb-demo.somedomain.com:27017,mongo2-pdb-demo.somedomain.com:27017/proxy-db-ft1?replicaSet=rs0&ssl=true&sslClientCertificateKeyFile=/etc/ssl/domain1234.pem&sslCertificateAuthorityFile=/etc/ssl/godaddy.pem

#### Log Messages

We got errors:

ERROR: <core> [db.c:168]: db_bind_mod(): SQL URL too long
ERROR: auth_db [auth_db_mod.c:173]: mod_init(): unable to bind to a database driver

### Additional Information

version: kamailio 4.4.7 (x86_64/linux)

**Comment by miconda** [comment]
I increased the max db url size check to 1023 instead of 255 via the commit referenced above. I will backport to 5.x, but 4.4 is out of maintenance, you have to backport in your local branch.

I will also review if this check is really necessary, at a quick look in the code, can be skipped all together.
