### ISSUE TITLE
 undefined symbol: SHA1

### ISSUE THREAD

**Issue by prabhat2k15** [kamailio/kamailio#1634]
when i run command "kamailio -c kamailio.cfg" I get this error..

loading modules under config path: /usr/lib/x86_64-linux-gnu/kamailio/modules/
 0(12737) ERROR: <core> [sr_module.c:576]: load_module(): could not open module </usr/lib/x86_64-linux-gnu/kamailio/modules/websocket.so>: /usr/lib/x86_64-linux-gnu/kamailio/modules/websocket.so: undefined symbol: SHA1

I tried reinstalling websocket modules but its not working.

**Comment by miconda** [comment]
What is the kamailio version and how you installed it?

What is the operating system?

Do you have libssl and libcrypto installed?

**Comment by prabhat2k15** [comment]
kamailio verison is 4.0
Operating System : Ubuntu 16.04
Yes, I have intalled both libssl and libcrypto  and other modules.

**Comment by miconda** [comment]
4.0 is a version not maintained for very long time.

Try with 5.0 or 5.1 which are the release series maintained at this moment and if the issue is still there, open an new item here. There are packages for 5.0 and 5.1 for Ubuntu flavours, see:

  * http://deb.kamailio.org/

This one is going to be closed not being a bug for a maintained version.
