### ISSUE TITLE
can't generate 487 reply when a final 408 was sent out

### ISSUE THREAD

**Issue by prabhat2k15** [kamailio/kamailio#1648]
kamailio verison is 5.1
Operating System : Ubuntu 16.04

Everyhting seems fine. Sip user is recieving the call but i am not getting any voice from that side. I dont know whether there is NAT issue or something else. I get this error in my log 

"tm [t_reply.c:479]: _reply_light(): can't generate 487 reply when a final 408 was sent out"

I have used dispatcher and wss connection.

**Comment by surendratiwari3** [comment]
it will be great if you can update more information like [incoming/outgoing]sip packet capture, kamailio logs.

**Comment by miconda** [comment]
It is clear by the log message that a final reply was already sent and no other one can be generated, the sip transaction being in terminated state. Can be due to use of many t_reply(), a network race between 408 and CANCEL.

If you want to discuss more and figure out the exact scenario, then use sr-users mailing lists. This tracker is for bugs in the code, not how to use kamailio/troubleshoot kamailio.cfg
