### ISSUE TITLE
rr module is_direction("downstream") and $ruid("dir") always evaluate downstream to true.

### ISSUE THREAD

**Issue by surendratiwari3** [kamailio/kamailio#1729]
### Description
we are using rr module with following parameter:

```
----- rr params -----
# set next param to 1 to add value to ;lr param (helps with some UAs)
modparam("rr", "enable_full_lr", 0)
# do not append from tag to the RR (no need for this script)
modparam("rr", "append_fromtag", 1)
```

after loose_route we are using following functions:

```
 local dir = headers.get("$rdir(name)")
 -- set the hangup initiator if BYE is from customer
 if dir == "downstream" then
     hangup_initiator = "caller"
 else
      hangup_initiator = "callee"
 end
```
its always printing the caller even if call is ended from the callee.

#### Reproduction
issue can be reproduced with above configuration set.

#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```
(paste your log messages here)
```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
(paste your output here)
```

* **Operating System**:

```
(paste your output here)
```

**Comment by miconda** [comment]
`KSR.rr.is_direction(...)` returns `1` if the direction is matching the parameter and `-1` if not. It does not return `true` or `false`, therefore be sure you do the appropriate comparison, it is different that kamailio.cfg language, where a negative return value is evaluated as false and positive is evaluate to true. In Lua, you have to do `<0` or `>0`.

Then, there is no function exported by kamailio `headers.get("$rdir(name)")`.

So overall, it looks like misunderstanding/misuse, rather than a bug in the code. You can discuss more or sr-users if you have further questions about using KEMI and Lua. If it proves to be a bug somewhere, then this can be reopen.
