### ISSUE TITLE
$sipt(redirection_number) evaluates the value as a numerical value

### ISSUE THREAD

**Issue by duarterocha91** [kamailio/kamailio#1789]
Greetings, 

I'm sorry if this isn't the right place to post this

$sipt(redirection_number) from module sipt evaluates the value  of redirection number as a numerical value however, it can contain hexadecimal values.

Best Regards

**Comment by miconda** [comment]
Iirc, this feature was contributed by @sergey-vb, maybe he can take a look instead of @tsearle and see what can be done.

**Comment by sergey-vb** [comment]
Hi All.
@duarterocha91, can you please check with change from commit https://github.com/sergey-vb/kamailio/commit/34fb47f28948e701c3ea98c673c8fb324b2f790e

**Comment by miconda** [comment]
@sergey-vb - you can merge that commit or make a pull request to be merged. It looks ok in my opinion and should be easier to test from main repo. The issue here is getting old without updates, so we can close it with your patch. Then if some new problem comes, can be reopened or a new issue created.

**Comment by sergey-vb** [comment]
Hi @miconda 

Done, PR #1859
