### ISSUE TITLE
Topos - Contact UUID

### ISSUE THREAD

**Issue by nicoonline** [kamailio/kamailio#1864]
### Description
Topos Module
Customise the UUID of the Call with a length & a separator.
Today the uuid has a static lenght and a "-" separator.

Contact: <sip:atpsh-5c710f13-961-51@IP>.

### Expected behavior
In a modparam, put the desired length and a separator or no separator.

#### Debugging Data

Contact: <sip:atpsh-5c710f13-961-51@IP>.

**Comment by miconda** [comment]
The data in contact username is encoded, each field there has its own purpose, so it requires to have a separator in order to work properly. All these are by design and required for current implementation. If you have some reasons to require such changes, discuss first on sr-users@lists.kamailio.org to see why such changes are need and what can be done for a solution.
