### ISSUE TITLE
Dispatcher probes a maximum of 15 Gateways at a time

### ISSUE THREAD

**Issue by duarterocha91** [kamailio/kamailio#2041]
### Description

I have a Kamailio with several Gateways configured. It's Probing is done using Dispatcher module and setting the GW state with value "8". If more than 15 Gw's are set as "8" with a probing frequency of 1min, only 15 GW will be probed each minute.

I can't find a configuration for this and have already posted this issue in the sr-users mailing list

I'm using Kamailio 5.2.0.

Best Regards

**Comment by miconda** [comment]
There is no limit in the module, afaik. Try to see if some gateways are in no probing mode via rpc command. Also, be sure you capture all the network interfaces or enable event_route[tm:local-request] and add there some log messages to see if local OPTIONS requests are sent.

You should upgrade to latest 5.2.x to be sure is not a side effect of some fixed bug since 5.2.0.

**Comment by duarterocha91** [comment]
Hello Daniel,

Thank you for answering. 

I have a print for each OPTIONS on local-request so Kamailio seems to be working fine.
I tried to disable my firewall and the issue disappeared. I have to look into it and find the real issue.

Since it's not a Kamailio problem i will be deleting this thread.

Thank you for your help

Best Regards

**Comment by miconda** [comment]
OK, good it was sorted out.
