### ISSUE TITLE
Cannot package on CentOS 8

### ISSUE THREAD

**Issue by sergey-safarov** [kamailio/kamailio#2078]
Several packages not exist in CentOS 8 repos.
Will wait until docker centos:8 image available and i will try fix

**Not existed deps**
```
nothing provides hiredis-devel
nothing provides GeoIP-devel
nothing provides mysql-devel
nothing provides python
nothing provides python-devel
nothing provides radiusclient-ng-devel
nothing provides squirrel-devel
nothing provides python2-rpm-macros
```

**Comment by sergey-safarov** [comment]
When packaged `libphonenumber` we get error
```
No match for argument: gtest-devel
No match for argument: protobuf-compiler
No match for argument: protobuf-devel
```
This error related to [16303](https://bugs.centos.org/view.php?id=16303) and [16301](https://bugs.centos.org/view.php?id=16301) CentOS tickets.

**Comment by sergey-safarov** [comment]
`CentOS:8` docker images released and now not available packages
```
No match for argument: python
There are following alternatives for "python": python2, python36
No match for argument: python-devel
No match for argument: radiusclient-ng-devel
No match for argument: squirrel-devel
```

**Comment by miconda** [comment]
Maybe for radius there are the other lib alternatives: radcli or freeradius client. I think the rpm specs use freeradius for opensuse. I know for debian is use radcli.

The squirrel-devel should not be needed, because app_squirrel has all the code embedded. Maybe this is a wrong dependency added in the specs.

As for python, try installing both python2 and python36, then see if there are python2-devel and python36-devel, both should be needed for app_python and app_python3.

**Comment by sergey-safarov** [comment]
Looks as CentOS 8 not have this packages:
```
hiredis
GeoIP
grpc
```

Until this packages is added I have disabled build for this kamailio modules on CentOS 8:
```
cnxcc
geoip
phonenum
redis
```
Ticket will close.
If issue not resolved, please reopen.
