### ISSUE TITLE
Play media when Kamailio+rtpengine are as an end point(not proxy)

### ISSUE THREAD

**Issue by bshirazi** [kamailio/kamailio#2315]
### Description

With rtpengine module play_media function  it is possible to play media to one of the endpoints(Kamailio is  normal proxy) but I like to use Kamailio+rtpengine as an end point playing music for caller(simple media server).

### Expected behavior
Possible to use Kamailio+rtpengine as an end point playing media.

### Possible Solutions
I see some efforts in mailing list trying to build/generate a 183 response inside script to simulate a dummy end point and then use rtpengine_play_media function.

Regards.
Babak

**Comment by henningw** [comment]
Have you looked into the rtp_media_server module?

**Comment by miconda** [comment]
Given that rtp_media_server module might provide what was requested here, but also because processing media is out of main scope for Kamailio project, I don't expect any current registered developer to commit to add this new feature in the near future. Therefore makes no sense to try to track its progress here, so i am closing it.

Of course, a PR with this feature will be considered to be merged, as any contribution that follows the licensing and contributing guidelines. Also, if any developer wants to work on this one in the near future and track the progress here, just reopen.

**Comment by bshirazi** [comment]
@miconda @henningw 
Hi 
Thank you for reply.
Would you please take a look at workaround way mentioned by ovoshlook here:
[https://github.com/sipwise/rtpengine/issues/870](url)
and help me doing same way ?

Regards
Shirazi
