### ISSUE TITLE
redis_cmd with more than 3 %s insertions causes parse error

### ISSUE THREAD

**Issue by dig12345** [kamailio/kamailio#2457]
### Description
Using more than 3 %s insertions in a redis_cmd() call causes kamailio to not start with parse errors.

### Troubleshooting
3 insertions works:

`redis_cmd("kam_redis", "SET %s %s-%s", "test_key", "foo", "bar", "r");`

4 does not:

`redis_cmd("kam_redis", "SET %s %s-%s-%s", "test_key", "foo", "bar", "bar2", "r");`

#### Reproduction
add this to cfg, run `kamailio -c`
`redis_cmd("kam_redis", "SET %s %s-%s-%s", "test_key", "foo", "bar", "bar2", "r");`

#### Log Messages

```
 0(30690) CRITICAL: <core> [core/cfg.y:3517]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 433, column 83: Too many arguments

 0(30690) CRITICAL: <core> [core/cfg.y:3517]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 433, column 83: '('')' expected (function call)
 0(30690) CRITICAL: <core> [core/cfg.y:3517]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 433, column 83: bad command: missing ';'?
 0(30690) ERROR: <core> [core/cfg.y:3363]: yyparse(): function used inside params of another function: xlog
 0(30690) CRITICAL: <core> [core/cfg.y:3517]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 435, column 9: use of function execution inside params not allowed

```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
version: kamailio 5.2.7 (x86_64/linux) 
flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144 MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: unknown 
compiled with gcc 5.4.0
root@vagrant-ubuntu-xenial-64
```

* **Operating System**:

Ubuntu 16.04

**Comment by miconda** [comment]
```
 0(30690) CRITICAL: <core> [core/cfg.y:3517]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 433, column 83: Too many arguments
```

Kamailio module functions support up to 6 parameters, this is by its current design of config interpreter. If someone wants to extend, has to make a PR.

The rest of error messages are printed because the interpreter tries to parse further to detect more errors.

Also the `redis_cmd()` is defined with only up to 6 parameters -- it is explicitly written in its docs:

  * https://www.kamailio.org/docs/modules/stable/modules/ndb_redis.html#ndb_redis.f.redis_cmd

```
Total number of arguments cannot exceed six.
```

If you need more parameters, try to use an embedded scripting language like Lua (app_lua) or Python (app_python3), they have their own redis client libraries that you can use.
