### ISSUE TITLE
tls.cfg: resolve macros

### ISSUE THREAD

**Issue by sergey-safarov** [kamailio/kamailio#2691]
### Description

I want use macros defined in `kamailio.cfg` inside `tls.cfg` like:
```
[server:[IPV6_ADDR]:5061]
method = TLSv1.2+
verify_certificate = yes
require_certificate = no
private_key = /etc/kamailio/tls/example.com.key
certificate = /etc/kamailio/tls/example.com.pem
server_name = example.com
server_name_mode = 1
```

This allows to minimize Kamailio config file adjustments inside cloud installations.

**Comment by miconda** [comment]
The code of interpreter for kamailio.cfg (action based rules) has nothing to do with reading tls.cfg (ini-like config).

While obviously the code is open source and one can contribute code to add any kind of feature, personally I don't see a value  to spend development effort to turn Kamailio in a generic text preprocessor for anything (there are also specific config files for dispatcher, permissions, ldap, ...), because there are many text pre-processor/templating tools like m4, jinja2,  that can be used to generate these files. This kind of template processing is also embedded in automated deployment tools such as ansible.

Therefore, if no other developer wants to engage in coding this feature request, it will be closed soon.

**Comment by sergey-safarov** [comment]
Thanks, Daniel @miconda for clarification.
Closing.
