### ISSUE TITLE
invalid json doc in command "kamctl ping"

### ISSUE THREAD

**Issue by christoph-v-kontron** [kamailio/kamailio#2781]
### Description

Hello Daniel,

https://lists.kamailio.org/pipermail/sr-users/2021-January/111628.html

> On Mon, Jan 18, 2021 at 4:19 PM Julia Bo <juliabo at gmail.com> wrote:
>
> It's my mistake, I checked a different branch. Sorry.
> Now I get the same result as yours.
> But in jason we get the result of command execution only and no sip reply
> result (that was in 4.4 : 200,408 etc..)
> I see sent OPTIONS and received reply in debug,
> Thank you,
> Julia

I have the same problem:
I get no sip reply result.

[root@vict2-ims3 scherney]# kamctl ping sip:node1.pcscf-1.vict-ims.net
{
  "jsonrpc":  "2.0",
  "result": {
  },
  "id": 12213
}

Hello,

I implemented an alternative rpc command that blocks waiting for the
response. Try again with latest master and let's see if works.

It waits for max 80secs for the sip reply to come back (or the transaction
to time out), checking every 0.1sec. Later I can make these values
modparams, for now just to validate it works.

Cheers,
Daniel

Can you please tell me, which commit it was, that I can test it at another version.
Thanks!

BR
Theo

#### Reproduction

[root@vict2-ims3 scherney]# kamctl ping sip:node1.pcscf-1.vict-ims.net
{
  "jsonrpc":  "2.0",
  "result": {
  },
  "id": 12213
}

#### Debugging Data

```none```

#### Log Messages

```none```

#### SIP Traffic

```[pr0071_030.zip](https://github.com/kamailio/kamailio/files/6648588/pr0071_030.zip)```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`
  * 
```
version: kamailio 5.1.6 (x86_64/linux) 42b01a
flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144 MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: 42b01a
compiled on 10:29:16 May 12 2021
```

* **Operating System**:

```
Linux vict-ims3 3.10.0-327.10.1.el7.x86_64 #1 SMP Sat Jan 23 04:54:55 EST 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by miconda** [comment]
When reporting a bug, it is important to actually describe the issue instead of pasting parts of a discussion that was months ago, because there were many changes in the c code and troubleshooting is not longer the same. Also, digging in archives takes time and support here is offered in a best effort manner. If the issue is reported properly, it has chances to be investigated. If the reporter expects the developers to do all the work to understand the problem, then it has lower chances to be approached.

Describe the bug as you face it these days, what happens with the latest versions in the supported branches, paste the logs and network traces if they are relevant.

**Comment by miconda** [comment]
Actually there is no need for further details. The email notification and description was lacking relevant details about Kamailio version because of wrongly formatted markdown when the issues was created. I edited it to format it and it revealed that the version is 5.1.6, which is a no longer maintained version. The new rpc command was added in the supported versions, 5.3 and 5.4 at that time, being also in 5.5. You will have to upgrade.
