### ISSUE TITLE
SIP Preconditions Settings?

### ISSUE THREAD

**Issue by JoelBorrego** [kamailio/kamailio#2866]
Hi GitHub Team,

We are trying to find how to disable the SIP Precondition flag in the Kamailio, because until now the only way to do any changes is via UE (Smartphones with debug SW).

According with the RFC3312 (https://datatracker.ietf.org/doc/html/rfc3312)

The SDP parameters are the following

   We define the following media level SDP attributes:

      current-status     =  "a=curr:" precondition-type
                            SP status-type SP direction-tag
      desired-status     =  "a=des:" precondition-type
                            SP strength-tag SP status-type
                            SP direction-tag
      confirm-status     =  "a=conf:" precondition-type
                            SP status-type SP direction-tag
      **precondition-type  =  "qos" | token
      strength-tag       =  ("mandatory" | "optional" | "none"
                         =  | "failure" | "unknown")**
      status-type        =  ("e2e" | "local" | "remote")
      direction-tag      =  ("none" | "send" | "recv" | "sendrecv")

Which one should be the equivalent in the Kamailio?, is the a specific module?

Br,

Joel

**Comment by miconda** [comment]
Questions about how to use kamailio, or what it can do, have to be addressed to sr-users@lists.kamailio.org mailing list.

This is the tracker to report issues in the c code.

**Comment by JoelBorrego** [comment]
Hi Daniel,

I already sent an e-mail to the ***@***.*** mailing lis,
but i didnt received any response.

Br,

Joel Borrego

**Comment by oej** [comment]
I guess that makes you pioneers when it comes to preconditions settings.
Don’t assume that the fact that you don’t get an answer means that we ignore you.

The readers of the list propably doesn’t know since preconditions is a feature that isn’t used a lot.

In general, Kamailio is not involved in offer/answer setup - it’s a proxy that just forwards sdp to the caller and another one back from the callee. In some cases, Kamailio will manipulate the SDP in transit.

Let this issue be closed and discuss further on the mailing list. 
/O
