### ISSUE TITLE
asan: load of misaligned address

### ISSUE THREAD

**Issue by sergey-safarov** [kamailio/kamailio#2914]
### Description
I have compiled Kamailio with ASAN and enabled alignment checks (`-fno-sanitize=alignment` do not used). 
And get error
```
core/cfg/cfg_script.c:120:10: runtime error: load of misaligned address 0xffff96900cdc for type 'struct cfg_script_var_t *', which requires 8 byte alignment
0xffff96900cdc: note: pointer points here
  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 04 00 00 00  00 00 00 00 00 00 00 00
              ^ 
```

I do not aware this is important or not.
Leave it for your review.

### Additional Information

Compiled 375f86b69e11cf835ae919873d3cd56f32d589c8
Arch aarch64

**Comment by miconda** [comment]
We do not aim for having all fields aligned, that's from the beginning of the project.

In this particular case, I tried to align it with commit 6857234c321faf33573e1a034ab666dc158eb549 .

Otherwise is not considered a bug. There are many "beautifications" that can be done playing with compiler options, many are nice to be done and if you want, just make pull requests.

**Comment by sergey-safarov** [comment]
Hello Daniel @miconda
I have tested this commit.
This helped to solve this error.

I found other similar error for another struct, but the approach you used do not help me for another struct.
Think I have not properly applied changes.

I close this.
