### ISSUE TITLE
Potential resource leaks (auth_identity, test code)

### ISSUE THREAD

**Issue by ryancaicse** [kamailio/kamailio#2983]
`fclose(pf);` should be put before `Line 295`?
https://github.com/kamailio/kamailio/blob/1ddc27f199061025a6a43da3e8a1388fcaddfe19/test/misc/code/shoot.c#L285-L297

**Comment by ryancaicse** [comment]
Similarly in this case
https://github.com/kamailio/kamailio/blob/a7bcf5bc2dafe797c0479d34df5e07d44d8dd438/src/modules/auth_identity/auth_identity.c#L350-L378

**Comment by ryancaicse** [comment]
https://github.com/kamailio/kamailio/blob/1ddc27f199061025a6a43da3e8a1388fcaddfe19/test/misc/code/shoot2.c#L371-L384

**Comment by henningw** [comment]
Thanks for the report. The two test files are probably no big issue, but the module is surely more important.

**Comment by miconda** [comment]
I pushed a commit for auth_identity for making it clean, because the code in is mod_inti and in case of errors, kamailio does not start, it shuts down and OS cleans up all resources. Moreover, I am not sure anyone uses it, the module is the implementation of the previous specs for caller identity, superseded by STIR/SHAKEN.

The test code is not used by kamailio app, it's just some testing case added by developers in early days of development for side testing. Upon review, probably most of them can be removed.

**Comment by ryancaicse** [comment]
@miconda Thank you for your efforts!!
