### ISSUE TITLE
Run kamailio in kubernates

### ISSUE THREAD

**Issue by maryamb99** [kamailio/kamailio#2988]
Hello everyone,
I have a problem over running local  docker images of Kamailio in Kubernate cluster..
Consider I build a local docker image from Kamailio and create a pod in one of my nodes . My process created successfully and Kamailio listen over port 5060 now I need to rebuild another docker image with new Kamailio configuration and run it as another pod with new name and listening over port 5061 but I have error "ImagePullBackOff" . I test this scenario many times but problem exists..
It is devastating for me and I need emergency help.

**Comment by fredposner** [comment]
Please remember that it is Christmas Eve and Christmas Day for the audience of the mailing list and many may not be reading emails. 

A google search shows this issue to be a Kunernetes error va something specific to Kamailio. 

“ The status ImagePullBackOff means that a Pod couldn't start because Kubernetes could not pull a container image. The 'BackOff' part indicates that Kubernetes will keep trying to pull the image, with an increasing back-off delay.”


Have you looked into any support lists for Kunernetes? 

-- Fred Posner

**Comment by miconda** [comment]
Questions about how to use kamailio should be addressed to sr-users@lists.kamailio.org, the issue tracker is for reporting bugs in the code.
