### ISSUE TITLE
xHTTP_PROM does not include metric_type

### ISSUE THREAD

**Issue by mneirynck** [kamailio/kamailio#3001]
### Description
We have a couple of Kamailio containers running on AWS ECS Fargate. Using a Cloudwatch Agent sidecar container I should be able to collect metrics from the Kamailio containers and push them to Cloudwatch for monitoring.

```
xHTTP_PROM exposes the metrics like this:
# Kamailio whole internal statistics
kamailio_app_python3_traced_replies 0 1640265350616
kamailio_app_python3_traced_requests 0 1640265350616
kamailio_core_bad_URIs_rcvd 0 1640265350616
kamailio_core_bad_msg_hdr 0 1640265350616
```

While other prometheus metrics I have seen are throwing metrics like this:
```
# HELP kamailio_shmmem_free_size Free shared memory.
# TYPE kamailio_shmmem_free_size gauge
kamailio_shmem_free_size {value} {timestamp}
```
### Troubleshooting
Cloudwatch error:
```
2022-01-12T21:16:38Z E! metric_type ERROR: kamailio_shmem_free_size|cwagent-ecs-file-sd-config|10.102.99.61:8080|  
```

### Possible Solutions
Have a look at the exporter Callr:
https://github.com/florentchauveau/kamailio_exporter

### Additional Information

Latest Kamailio built from source on a Debian base image

**Comment by vhernando** [comment]
Hello mneirynck,

in Prometheus metrics when there is no # TYPE metadata it defaults to UNKNOWN metric type. This is suitable for xHTTP_PROM because it blindly takes Kamailio registered counters and export them. We do not know if they are Prometheus counters or if they are Prometheus gauges. 

Currently OpenMetrics recommend not to use UNKNOWN metric types 
https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#unknown 
and Cloudwatch do not support unknown Prometheus metrics 
https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/ContainerInsights-Prometheus-metrics-conversion.html

On the other hand kamailio_exporter exports a set of metrics and defines clearly if they are counters, gauges, etc. So at this moment I recommend you to use kamailio_exporter to interface with Cloudwatch
https://github.com/florentchauveau/kamailio_exporter/blob/master/collector.go

**Comment by mneirynck** [comment]
Hi,
Sad we have to resort to a third party for this.
Just tested the exporter and it's also failing because it starts instantly without waiting for the Kamailio container and fails because Kamailio doesn't respond in time.

So we either write our own exporter, or use a script which we run on xHTTP requests to /metrics.

We'll figure it out, but this would have been a very useful feature for us.
I'll hear it if the feature ever gets added to xHTTP_PROM!

Thanks for your descriptive feedback.

**Comment by vhernando** [comment]
Hello mneirynck,

I am thinking on a workaround. Does asigning gauge type to Kamailio's metrics even if they are actually counters would suit you?

**Comment by mneirynck** [comment]
Not sure if that would work for Cloudwatch, since gauges can go up and down while counters can't. No idea how they check this, if they check it at all.

In the meantime we've implemented our own script that exposes metrics to Cloudwatch directly, without prometheus. So if nobody else needs this feature it can go on hold.

**Comment by miconda** [comment]
@vhernando: do you still want this open to work on something related to it, or can it be closed based on @mneirynck comment?

**Comment by vhernando** [comment]
Hello Daniel, 
I think we can close the issue.
