### ISSUE TITLE
Retrieve the current debug level with KEMI kex module

### ISSUE THREAD

**Issue by smurfix** [kamailio/kamailio#3030]
### Description

While the `kex` module exports a way to temporarily change the debug level, it cannot retrieve the current level.

### Expected behavior

I can write Python code like this:
```
    if KSR.kex.getdebug() > 2:
        ... # generate detailed and somewhat-time-consuming debug output
        ... # which would just get dropped on the floor otherwise
```

#### Actual observed behavior

If there is a way to get Kamailio's current and/or configured debug level, I didn't find it.

**Comment by miconda** [comment]
Questions about configuring, using or what features are available in kamailio should be addressed to sr-users@lists.kamailio.org mailing list. This is for reporting bugs in C code and track development of new features. It helps to have a proper focus on development related tasks and the sr-users has a larger community with experienced users of Kamailio, here are mainly the developers.

Otherwise, there are functions exported by kamailio core to Kemi, not only by kemix or other modules, one is doing what you need, KSR.get_debug()
