### ISSUE TITLE
usrloc OPTIONS not tracing with HEP

### ISSUE THREAD

**Issue by lukeescude** [kamailio/kamailio#3136]
### Description

OPTIONS keepalives sent by usrloc are not being traced with HEP/Homer 

#### Reproduction

Module setup:

modparam("siptrace", "duplicate_uri","sip:HOMERIP:9060");
modparam("siptrace", "hep_mode_on",1);
modparam("siptrace", "trace_to_database",0);
modparam("siptrace", "trace_flag",22);
modparam("siptrace", "trace_on", 1);
modparam("siptrace", "hep_version", 3);
modparam("siptrace", "trace_mode", 1)

I believe the above setup should duplicate ALL packets to homer, which is working just fine, except for usrloc-generated OPTIONS.

The 200 OK from endpoints is showing up just fine, just not the initial request.

Kamailio version 5.5

**Comment by miconda** [comment]
The module uses its own sending functions to optimize performances (e.g., not to increase the list of active transactions) and by that the siptrace hooks are not intercepting them.

Response are seen by siptrace because they come in via network to the listen sip port.

There are other places that send data directly, which also doesn't get in the siptrace callbacks, but the code is open source and one can make pull requests to add siptrace support where is needed.
