### ISSUE TITLE
dialog module does not update callee tag until 2xx received, is_known_dlg() return false for early dialogs

### ISSUE THREAD

**Issue by patrickarton** [kamailio/kamailio#3155]
### Description
dialog module does not update callee tag until it receives a 2xx response to an INVITE.
and so we can not use **is_know_dlg()** function for in-dialog request like UPDATE when the session is still in early state.

#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```
(paste your log messages here)
```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
kamailio 5.5.4
```

* **Operating System**:

```
(paste your output here)
```

**Comment by miconda** [comment]
This is by design and I don't think it is something that could be easily changed given the cases of parallel (or serial) forking involving many branches with many replies (and tags). Even when kamailio sends out a branch, next can be another proxy with serial/parallel forking and again many replies with different tags.

The dialog is fully created on 200ok. Before is just early-dialog state, collecting the data needed for established state.

**Comment by henningw** [comment]
Good point. I was just noticing it after porting some configuration from another SIP server which aparently supported that. Changed the issue to a feature request, lets see if somebody can work on that.
