### ISSUE TITLE
long type support

### ISSUE THREAD

**Issue by sergey-safarov** [kamailio/kamailio#3172]
### Description

When I use Kamailio 5.6 with kazoo config file, then can see error messages:
```
WARNING: <core> [core/rvalue.c:1043]: rval_get_int(): automatic string to int conversion for "63823655406" failed
WARNING: <core> [core/rvalue.c:1949]: rval_expr_eval_int(): rval expression conversion to int failed (140,54-140,73)
```
This warning message related to commit bcd59d73e2fc5ae8e14cad520e726ef431f0563f.
Kazoo sending timestamp using the Gregorian format and timestamp value greater than max int value.
As a result, JSON string values with a timestamp cannot be parsed and converted to int.

As I understand required to add long format support into Kamailio.
This was tested using this Kamailio config.
```
listen=udp:127.0.0.1:5060

######## Advanced logger module ########
loadmodule "xlog.so"

######## Generic Hash Table container in shared memory ########
loadmodule "htable.so"

event_route[htable:mod-init] {
  if ( 63823655406 > 0 ) {
    xlog("L_ERR", "*** Kamailio support long data type!\n");
  } else {
    xlog("L_ERR", "*** Kamailio not support long data type!\n");
  }
}
```

### Expected behavior
Kamailio is able to convert strings to long data type.

#### Actual observed behavior
Kamailio was not able to convert strings to long data type.

@lazedo, probable you want to know about this behavior.

**Comment by miconda** [comment]
I assume it is about script operations, not kazoo module code.

The core interpreter supports int for the moment, probably has to be update to use long, but if nobody else starts to do it, then it may take quite some time because I am quite busy during next period of time with the summer holidays just starting.

The solution right now is to use some embedded scripting language, like javascript via app_jsdt (which does not require external libraries and has good support for json parsing).

I am setting it as feature request, if nobody takes over its development, it me be closed after a while.

**Comment by miconda** [comment]
Implementation of long support started at Kamailio Devel meeting in November and should be done for most of the code. If there are problems found, then open a new issue with corresponding details.
