### ISSUE TITLE
Building a json/rest module

### ISSUE THREAD

**Issue by debackel** [kamailio/kamailio#318]
Any plans to build a json/rest over http module?
There is such a module over rpc, but not over http.

Could the http_query module be used as a basis for such a module? Potentially with https and basic authentication?

**Comment by miconda** [comment]
Olle (@oej) has developed a dedicated module for http operations using curl library. It is on a personal branch:

  * https://github.com/kamailio/kamailio/tree/curlmod/modules/curl

Olle planned to merge it to master for a while, looks like he has to do it soon, because that module would be a better foundation. Then using modules such as json or jansson, a json response can be handled in the config file.

**Comment by oej** [comment]
Yes, this module was built for restful API solutions with some improvements. There's still a lot to do, but it's a foundation we can work on.

**Comment by oej** [comment]
Committed a first version to trunk. Please test it. 

Closing this issue for now.

**Comment by debackel** [comment]
Hi,
Thanks for the module, I believe it is a great foundation for implementing web services (JSON/REST) clients.
Did you keep it tuned to the latest changes to the "http_query" utils module function  (in particular the http_response_trim  parameter)?
Best regards,
Laurent.

**Comment by mgwilliams** [comment]
I was looking at this last night. Are their plans to make it async? The index entry in the docs says it is, but I didn't see a resume route param.
