### ISSUE TITLE
accounting module inserts random data into reason header fields

### ISSUE THREAD

**Issue by henningw** [kamailio/kamailio#3287]
The accounting module seems to inserts random data into reason header fields, see attached screenshot.

This was observed after an upgrade to Kamailio 5.5.4 from an 5.4.9. I did a quick review of the changes between both branches, and the commit c5f6ff37f61f99e0 seems to be touching this functionality.

It might be some missing initialization for the locally generated replies reason phrase.

![grafik](https://user-images.githubusercontent.com/6481937/204288275-9e937539-c242-43fa-babd-f098a3542940.png)

**Comment by henningw** [comment]
Actually its the same problem as in #2981 reported. Its already fixed in git master, will backport the commit to 5.5.

**Comment by henningw** [comment]
Should be fixed in 5.5 branch also now by 0ad72e16757e8

**Comment by miconda** [comment]
Remember that you have to cherry-pick from the next upper stable branch (in this case from branch 5.6), if it is not the latest stable branch, because it keeps tracks of all cherry-picks, allowing to compare with all upper stable branches as well as with master in order to find easier what commits are backported or not.
