### ISSUE TITLE
file_read() and file_write() contain no documentation on return values

### ISSUE THREAD

**Issue by dilyanpalauzov** [kamailio/kamailio#3314]
According to https://www.kamailio.org/docs/modules/5.6.x/modules/corex.html#corex.f.file_read  the functions cores.file_read() and cores.file_write() do not return a value (return void).  The examples after functions are `if (file_write("z', "z")) {...}`.  Since the functions appear in `if ()` they return se value.

* document the return values of both functions

**Comment by miconda** [comment]
While in generally it would be good to have the return codes explicitly in readme, it is not a requirement. Having a report on tracker for each function is not feasable, if one wants to document, the source code is available and PRs can be made.

Otherwise, as general rule, if a function succeeds, returns positive (true) and if it fails, returns negative (false).
