### ISSUE TITLE
ERROR: mediaproxy [mediaproxy.c:1978]

### ISSUE THREAD

**Issue by dhngoc** [kamailio/kamailio#347]
Now I took a look kamailio and get the error: Sep 29 11:28:37 lvps46-163-74-198 /usr/local/sbin/kamailio[1738]: ERROR: mediaproxy [mediaproxy.c:1978]: EngageMediaProxy(): engage_media_proxy requires the dialog module to be loaded and configured.

I don't know what it is, please help me.

**Comment by miconda** [comment]
You have to load and configure dialog module.

This kind of questions should be addressed to sr-users@lists.sip-router.org mailing list, being Kamailio admin question related to config rather than a bug in source code. I am closing this issue, if you need further clarification, write an email to mailing list.
