### ISSUE TITLE
Function `sdp_mangle_ip("IP/MASK","IP")` Malfunction

### ISSUE THREAD

**Issue by teamwcp** [kamailio/kamailio#3554]
I have been trying to replace the SDP connection IP with some other IP using module `mangler` (`Kamailio v5.7.0`). But It seem like its malfunctioning
```
if ($rs == 200) {
                xlog("L_INFO", "200 $rm Detected");
                sdp_mangle_ip("192.168.0.132/24","8.8.8.8");
 }
```
and results I received are like this below
```
v=0 o=- 107808851201429815 2 IN IP4 192.168.0.132 
s=- t=0 0 
m=audio 24794 RTP/AVP 0 8 101 
c=IN IP4 192.168.0.1328.8.8.8 
a=mid:audio 
a=sendrecv 
a=rtpmap:0 PCMU/8000 
a=rtpmap:8 PCMA/8000 
a=rtpmap:101 telephone-event/8000 
a=ssrc:822878909 cname:0ZfUBhl8cMeHaeVl 
a=nortpproxy:yes
```

I first ask the same question in mailing list `sr-users@lists.kamailio.org` but after waiting for some time (>24hrs) i cant see my question on on forum, that why I open a ticket here.

**Comment by miconda** [comment]
Mailing list is not a premium/paid support channel, people respond there in a best effort manner. Not getting a response there does not mean that there are people answering on the bug tracker, because this one is for reporting issues in the c code. See the next comment, likely it is the same case:

  - https://github.com/kamailio/kamailio/issues/3555#issuecomment-1708653171
 
Discussing further has to be done on the mailing list.
