### ISSUE TITLE
TOPOS callid masking

### ISSUE THREAD

**Issue by Den4t** [kamailio/kamailio#3606]
### Description
PKG memory errors when configured mask_callid in TOPOS.

### Troubleshooting

The poblem in detail desribed in mailing lists:
https://www.mail-archive.com/sr-users@lists.kamailio.org/msg19997.html

### Possible Solutions

Right way to configure topos for callid masking is:

modparam("topoh", "use_mode", 1)
modparam("topos", "mask_callid", 1)
modparam("topoh", "mask_callid", 1)

We need to set mask_callid module parameter for topoh also. There is not a word about this in the documentation,
so docs correction needed.

### Additional Information

  * **Kamailio Version** - 5.7.X

**Comment by miconda** [comment]
Setting mask_callid should not be needed, was mistakenly checked in the intermodule API function. I pushed a commit (referenced above) to remove it.

If it is that easy to reproduce, once it happens, trigger printing of memory status in the syslog and then paste the corresponding log messages here. See:

 - https://www.kamailio.org/docs/modules/stable/modules/corex.html#corex.rpc.pkg_summary

To make it easier, set `childred=1`, reproduce and spot the pid of the process printing the out of memory message. Run the above rpc command for that pid. You still need to send some SIP traffic to get the command executed, because it depends on next processed packet.

**Comment by Den4t** [comment]
Hi !

Thanks for the fix.
Can't check this right now.

**Comment by miconda** [comment]
I just did a few tests using Kamailio for git master branch with topos and mask_callid=1, all seemed ok, call id is masked and unmasked fine, calls were established and ended fine.

I am closing this one, if you still have issues, reopen (or create a new) issue, add again the log messages you get with latest version, a pcap with sip traffic would help as well.
