### ISSUE TITLE
RFE: RPM packaging of wolfSSL 5.6.6 for upcoming freeze/5.7 release

### ISSUE THREAD

**Issue by space88man** [kamailio/kamailio#3713]
### Description
Request the RPM packaging of wolfSSL 5.6.6 for the upcoming freeze

### Expected behavior
I intend to bump the internal submodule to 5.6.6 and it would be good if Kamailio RPM packages could be updated.

ping @sergey-safarov

**Comment by sergey-safarov** [comment]
@space88man do I understand properly you want package wolfssl module in the 5.6.6 release?

**Comment by sergey-safarov** [comment]
And update dependent wolfssl RPM package?

**Comment by space88man** [comment]
Hi @sergey-safarov—for kamailio RPMs I suggest not to use external OS packages like wolfssl-5.6.[346]—the reason is that wolfssl does not support semantic versioning and will bump the soname even with a minor release: e.g. 5.6.4 -> soname 41 5.6.6 -> soname 42. This non-standard distro packaging behaviour was raised by the Alpine Linux maintainer: https://github.com/wolfSSL/wolfssl/issues/7088 

User could not "dnf upgrade" from 5.6.[34] to 5.6.6.

It might be easier for end users if you were to  package with `WOLFSSL_INTERNAL=yes`.

> And update dependent wolfssl RPM package?

**Comment by space88man** [comment]
1. 5.7 cannot use external packaging due to shm 16-byte requirement
1. For 5.8 - recommend packaging v5.6.6-stable with the name "wolfssl42" to match debian

**Comment by sergey-safarov** [comment]
> the reason is that wolfssl does not support semantic versioning and will bump the soname even with a minor release: e.g. 5.6.4 -> soname 41 5.6.6 -> soname 42. 

I think it is managed by the wolfssl rpm package in kamailio repo.
When we update wolfssl and then build new kamailio release, then kamailio-wolssl package will be linked with correct wolssl package.
Please check [`kamailio-tls_wolfssl-5.8.0-0.el9.centos.x86_64.rpm`](https://rpm.kamailio.org/centos/9/master/master/x86_64/Packages/k/kamailio-tls_wolfssl-5.8.0-0.el9.centos.x86_64.rpm) `REQUIRES` content
```
libc.so.6()(64bit)  
libc.so.6(GLIBC_2.14)(64bit)  
libc.so.6(GLIBC_2.2.5)(64bit)  
libc.so.6(GLIBC_2.33)(64bit)  
libm.so.6()(64bit)  
libwolfssl.so.41()(64bit)  
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsZstd) <= 5.4.18-1
rtld(GNU_HASH)  
```
So, when this package was selected for update it automatically tried to install `wolfssl` package which provides
```
libwolfssl.so.41()(64bit)  
```
And required wolfssl rpm package is located in the same repo.
I prefer to use a dedicated package because when need to analyze the core stack will be easier to install and use debug files for a dedicated package instead of a statically linked file.

"dnf update" will work you execute the simultaneous update of kamailio and wolfssl.
But does not work if the same server installed other programs that use old wolfssl ABI.
In this case, static linking will be an option. But it is a very rare case.
