### ISSUE TITLE
Consider adding socket options SO_BINDTODEVICE when the interface name is given for listen in the config file

### ISSUE THREAD

**Issue by toharish** [kamailio/kamailio#3716]
### Description
Consider adding socket options SO_BINDTODEVICE when the interface name is given for listening in the config file. This will be useful in listening to linux VRF interfaces, especially when there are two different VRFs and it is required to proxy SIP messages between the VRFs

**Comment by miconda** [comment]
Kamailio needs to know the IP address of the socket in order to set in the SIP routing headers. When interface name is provided, Kamailio discovers its IP address to listen on it. If SO_BINDTODEVICE can be done with preserving proper working for SIP routing, then anyone is welcome to make a PR with such addition.
