### ISSUE TITLE
registrar: Consider changing default setting for case matching of username

### ISSUE THREAD

**Issue by mtryfoss** [kamailio/kamailio#3719]
### Description

I've recently spent some time debugging a case with JsSIP and usernames in form of a generated string which can be both upper and lower case letters plus digits.

On BYE from callee to JsSIP, it responded with a "404" and "Request-URI does not point to us" in the console while debugging.
JsSIP is using the Contact returned in the 200 OK to REGISTER (which is transformed to all lower case) for new outgoing INVITE.
It does not match this against the one used in BYE correctly, and return "404".

I see there is a setting in the registrar about this:
```
3.11. case_sensitive (integer)
If set to 1 then AOR comparison and also storing will be case sensitive, if set to 0 then AOR comparison and storing will be case insensitive.
This is recommended. This parameter can be modified via Kamailio config framework.

Default value is 0.
```

Since the RFC states that username should be handle case-sensitive, maybe it would be smart to change this default?
```
Comparison of the userinfo of SIP and SIPS URIs is case-
         sensitive.  This includes userinfo containing passwords or
         formatted as telephone-subscribers.
...
   The URIs within each of the following sets are not equivalent:

   SIP:ALICE@AtLanTa.CoM;Transport=udp             (different usernames)
   sip:alice@AtLanTa.CoM;Transport=UDP
```

#### Reproduction

Make a registration with a username containing both upper and lower case characters. It will be stored in all lower case.

### Possible Solutions

Change default value.

Regardless of the outcome on this case - at least now there is a note about it here too.

**Comment by miconda** [comment]
Iirc, the decision to make it case insensitive by default, unlike the RFC specifies, because of user experience when using names as user identity. Usually the UA (e.g., desktop or smartphone app) they do autocorrect to camel-case the names. So if one wants to dial `alice`, the app is changing it to `Alice`. It was also considered that having `alice` and `Alice` as different users to be unlikely desirable. Moreover, for telephone numbers, matching is the same.

In the context of random-gemerated alphanumeric user ids, it can lead to conflicts indeed. However, as this setting has this value for very long time, I would rather keep it as it is, because there were not many complaints about it in the past. Changing it may bring some unexpected call failures for existing deployments.

**Comment by mtryfoss** [comment]
Ok. Closing then :) At least there's ticket now regarding the issue.
