### ISSUE TITLE
uac: bad error in log

### ISSUE THREAD

**Issue by snen** [kamailio/kamailio#643]
there is define in uac_reg.c (define reg_db_set_attr(attr, pos)) which may generate logs like this:
> empty value not allowed for column[2]='l_domain' - ignoring record

really, record was added, so it should be converted to WARNING or it is neсessary add any more restrict logic

**Comment by miconda** [comment]
I guess you used it to refresh one record, because the process of loading the records at startup should ignore such records. reg_db_set_attr() triggers 'continue' in such case and it is used in a for-loop.

I am going to push a patch that will ignore also for the refresh operation. In that case reg_db_set_attr() was used alone, not within a loop.

**Comment by snen** [comment]
it is  startup error also

**Comment by miconda** [comment]
It is error indeed, but the record should not be added in that case, right?

**Comment by snen** [comment]
record is added
kamcmd> uac.reg_dump 
{
	l_uuid: 000112838
	l_username: 000112838
	l_domain: 
	r_username: 000112838
.......
	flags: 20
...........

}

**Comment by miconda** [comment]
Obviously -- reg_db_set_attr() is a while loop itself so the continue applied there.

Pushed another patch -- can you test it? If all ok, I will backport.

**Comment by snen** [comment]
it works as expected, thanks!

**Comment by miconda** [comment]
Thanks for reporting and testing, I will backport.

While it could have been ok without domain, the other attributes are important and same check was done for all.
