### ISSUE TITLE
tm: missing RPC commands from README

### ISSUE THREAD

**Issue by ovidiusas** [kamailio/kamailio#772]
The follwoing RPC commands should be documented in the tm README file:
tm.cancel
tm.hash_stats
tm.reply
tm.stats
tm.t_uac_start
tm.t_uac_wait

**Comment by miconda** [comment]
The rpc commands are indexed at:

  * http://www.kamailio.org/docs/docbooks/devel/rpc_list/rpc_list.html#rpc_exports.tm

It is an aim to add sections in the readmes, but it was not enforced because the documentation for them was generated from sources.

So this is not a tm only issue, needs to be addressed at a whole.
