### ISSUE TITLE
auth_db Deprecate email_address in database schemas

### ISSUE THREAD

**Issue by oej** [kamailio/kamailio#858]
I suggest we delete the "email_address" field in database schemas for auth_db. I think it was put there as an example of extendability but a lot of users seems confused about this and Kamailio by default does not use that field at all.

Any opinions? If we reach an agreement we'll produce patches and clean up the various schemas.

**Comment by miconda** [comment]
I guess it was more or less left from the serweb time, for the integration with sems for voicemail email notifications. I am fine to be removed.

I am not use if keeping *rpid* column is of any use as well.

Anyhow, kamctl needs to be checked if has side effects of any of these columns when removed.

**Comment by amessina** [comment]
I use the rpid column (though I use it to set P-Asserted-Identity instead),  and have also extended the table to associate other subscriber-level items with a particular account, such as account number, PAI when routed to an "external" entity, etc.  What about seeing what other columns folks have added on the mailing list?

**Comment by oej** [comment]
In my view, we should not - I want to remove these from the default schema. What you add and others add is up to their configuration.

**Comment by amessina** [comment]
@oej, it's absolutely reasonable to remove columns from the default schema.  But I do think it would be good, especially for new users, to better highlight the fact that auth_db (and the subscriber table) is easily extendable for an implementation's own purposes.  For me coming to Kamailio as a new user, there are so many ways to accomplish the same task--when I finally realized I could just extend the subscriber table since auth_db has flexible support for doing so, it made things a lot simpler to get started.

**Comment by oej** [comment]
Agree fully. I just love good documentation. Why don't we clean up the default schema and add an extended version to the README? That would show what can be done.

**Comment by amessina** [comment]
@oej, that is a perfect idea.  Thank you.

**Comment by miconda** [comment]
Committed.
