### ISSUE TITLE
Kamailio IMS installation guide and WebRTC support

### ISSUE THREAD

**Issue by aoncorici** [kamailio/kamailio#860]
Dear all, my name is Ancuta Corici (Onofrei) and am working at Fraunhofer FOKUS. We might have met or you might have seen some code from me in OpenSER and OpenIMSCore (e-cscf, support for offline charging). 
We have now @ngvoice and many others to carry on the work on IMS and we send our greetings.
We are working now in the EU project reTHINK and would like to use kamailio ims for interop between webrtc clients and ims world.

For the moment, we are evaluating the status of IMS components and WebRTC support. Thus, we would like to know:
- if there is a more updated version on the installation info than http://www.kamailio.org/wiki/tutorials/ims/installation-howto?s[]=ims

- info on the configuration example file

- if there is a know-how on kamailio IMS and WebRTC support or intent to support it, as described on page 29 in http://www.etsi.org/deliver/etsi_ts/124300_124399/124371/13.04.00_60/ts_124371v130400p.pdf 

@ngvoice : might be the best to answer, but if somebody else is having the info, we are open.

**Comment by ngvoice** [comment]
Hi Ancuta,

I can only pass back the greetings to you and all of the OpenIMS-Core team. Without your effort, we would not have the feature-set of Kamailio IMS, that we have now.

We plan to update/publish a new version of the installation tutorial and the example configs, but due to a tight schedule (I have a one-year old son, I do some amateur acting +  we have a full order book), that will likely have to wait for January next year. We have several enhancements we will publish (e.g. a Online-Charging-Server (Ro for Pre- and Postpaid), a refurbished HSS, Management-Tools, ...).

We showed WebRTC on IMS during KamailioWorld this year. The configuration for this is in the example files. However, those examples were simply working as another endpoint, so the full SIP-credentials are required. I haven't used it since, but I guess it should still work. I haven't checked with the ETSI/3GPP Spec in detail; we are usually a bit more pragmatic on those topics.

We are currently deploying WebRTC with two mobile operators in Europe (no IMS/VoLTE involved) and VoLTE for two mobile operators around the world, which keeps us quite busy at the moment. It pays our bills, but also slows us down on publishing our enhancements to the public.

Interop between VoLTE, WebRTC, legacy SIP and the rest of the legacy world worked in April 2016 and it "should" still work. However, WebRTC Interop is however currently untested from our side. There was someone on the mailing-list recently, who tried it and had it working.

Thanks,
Carsten

**Comment by aoncorici** [comment]
Hi Carsten,

Thank you for sharing, and congratulations! I will give it a try in the next weeks and get back to the mailing list/issue list if in trouble.

Keep up the good work,
Ancuta

**Comment by aoncorici** [comment]
Hi Carsten,

For more orientation, can you tell me which webrtc client and which IMS client you used in the demonstration.

if still in the memory, can you share the info on the git commit that was used for the demo.

And another question: was it working both directions: webrtc to IMS and IMS to webrtc.

Thank you for your help,
Ancuta

**Comment by ngvoice** [comment]
Hi Ancuta,

i used SIP.js as a very simple Webfrontend, we even had the credentials hard-coded.

It must have been this commit:
https://github.com/kamailio/kamailio/commit/5169e7dae017bdd4cb66dda388e78127efb51aa6

It has been working both direction (WebRTC to IMS and IMS to WebRTC).

Thanks,
Carsten

**Comment by oej** [comment]
This is a discussion that works better on the mailing list than the bug tracker - as it is not an issue, just general questions.

**Comment by miconda** [comment]
Closing it here, further discussions can be done on sr-users mailing list.
