### ISSUE TITLE
cdp: hardcoded values used for ranks in forked processes

### ISSUE THREAD

**Issue by ovidiusas** [kamailio/kamailio#973]
The cdp module creates several processes for workers, receivers, acceptors ...
All this processes have random ranks.
It seems that the rank for all this processes has no special meaning and therefore the forking should be done using the PROC_NOCHLDINIT rank and not a random hardcoded one.

**Comment by miconda** [comment]
If the rank is >0, it is initialized like a sip worker, doing all the child_init() for sip workers. So it may need db connectivity and all the rest there. The rank starts from 1001, which I think is not overlapping in anything dangerous. I think this is fine for now. Maybe a define can be introduced instead of 1001, but this can just be a normal enhancement.

I am closing this issue, if anyone has more to add and still consider it an issue, reopen.
